spring.application.name=demo
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=Proyecto-DWI
management.endpoint.health.show-details=always
# Solo si tienes seguridad activa:
# spring.data.mongodb.username=admin
# spring.data.mongodb.password=secreto